---
- name: devSetup Playbook
  hosts: all
  become: true
  vars:
    ansible_become_pass: "{{ ansible_sudo_password }}"
  tasks:
    - name: Include devsetup
      ansible.builtin.include_role:
        name: devsetup
