---
- name: Get join Command
  ansible_hosts: master
  become: yes
  gather_facts: false
  shell: kubeadm token create --print-join-command
  register: join_command_raw

- name: Set Join Command
  set_fact:
       join_command: "{{ join_command_raw.stdout_lines[0] }}"

- name: join cluster
  ansible_hosts: workers
  become: yes
  shell: "{{ hostvars['master'].join_command }} >> node_joined.txt"
  args:
     chdir: $HOME
     creates: node_joined.txt

