- hosts: localhost
  gather_facts: no
  vars_files:
    - awskeys.yml
  tasks:
    - name: Create new EBS Volume
      ec2_vol:
        aws_access_key: "{{ AWS_ACCESS_KEY_ID }}"
        aws_secret_key: "{{ AWS_SECRET_ACCESS_KEY }}"
        region: "{{ AWS_REGION }}"
        zone: ap-southeast-1a
        volume_size: "50"
        name: app_volume
        device_name: /dev/sda1
      register: vol_info
    - debug:
        var: vol_info
