---
- name: create the 'kubernete' user
  user: 
    name: kubernete 
    append: yes 
    state: present 
    createhome: yes 
    shell: /bin/bash

- name: allow 'kubernete' to have passwordless sudo
  lineinfile:
         dest: /etc/sudoers
         line: 'kubernete ALL=(ALL) NOPASSWD: ALL'
         validate: 'visudo -cf %s'
- name: set up authorized keys for the kubernete user
  authorized_key: user=kubernete key="{{item}}"
  with_file:
      - ~/.ssh/id_rsa.pub
