- hosts: localhost
  become: true

  tasks:
     - name: Add Docker GPG Key
       apt_key: 
         url: https://download.docker.com/linux/ubuntu/gpg

     - name: Add docker repository
       apt_repository:
               repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ansible_distribution_release}} stable

     - name: Install the package
       apt:
          name: "{{ item }}"
          state: present
          update_cache: yes
       with_items:
           - apt-transport-https
           - curl
           - software-properties-common
           - ca-certificates
           - docker-ce
