- hosts: localhost
  gather_facts: yes
  vars_files:
    - awskeys.yml
  tasks:
    - name: Change state of EC2 instances by tag
      ec2:
        aws_access_key: "{{ AWS_ACCESS_KEY_ID }}"
        aws_secret_key: "{{ AWS_SECRET_ACCESS_KEY }}"  
        region: "{{ AWS_REGION }}"
        state: running
        instance_tags:
          Name: Test
