- hosts: localhost
  gather_facts: no
  vars_files:
    - awskeys.yml
  tasks:
    - name: Create new IAM user
      iam:
        aws_access_key: "{{ AWS_ACCESS_KEY_ID }}"
        aws_secret_key: "{{ AWS_SECRET_ACCESS_KEY }}"
        region: "{{ AWS_REGION }}"
        iam_type: user
        state: present
        name: ansibleuser
        password: myuser@123ansible!
