- hosts: localhost
  gather_facts: no
  vars_files:
    - awskeys.yml
  tasks:
  - name: create a new VPC with dedicated tenancy
    ec2_vpc_net:
      aws_access_key: "{{ AWS_ACCESS_KEY_ID }}"
      aws_secret_key: "{{ AWS_SECRET_ACCESS_KEY }}"
      region: "{{ AWS_REGION }}"
      name: TestVPC
      cidr_block: 10.20.0.0/16
      tags:
        client: test
      tenancy: dedicated
