- hosts: localhost
  gather_facts: no
  vars_files:
    - awskeys.yml
  tasks:
    - name: Gather snapshot facts
      ec2_snapshot_facts:
        aws_access_key: "{{ AWS_ACCESS_KEY_ID }}"
        aws_secret_key: "{{ AWS_SECRET_ACCESS_KEY }}"
        ec2_region: "{{ AWS_REGION }}"
    - name: Create Snapshot of Volume
      ec2_snapshot:
        aws_access_key: "{{ AWS_ACCESS_KEY_ID }}"
        aws_secret_key: "{{ AWS_SECRET_ACCESS_KEY }}"
        ec2_region: "{{ AWS_REGION }}"
        instance_id: YOUR_INSTANCE-ID
        device_name: /dev/sda1
        state: present
        description: "Taking volume backup on demand."
