- hosts: localhost
  gather_facts: no
  vars_files:
    - awskeys.yml
  tasks:
    - name: Create new IAM role in AWS Account
      iam_role:
        aws_access_key: "{{ AWS_ACCESS_KEY_ID }}"
        aws_secret_key: "{{ AWS_SECRET_ACCESS_KEY }}"
        region: "{{ AWS_REGION }}"
        name: automationRole
        assume_role_policy_document: "{{ lookup('file','policy.json') }}"
        description: This role was created by Ansible Automation.
      register: iam_role
    - debug:
        var: iam_role
