- hosts: localhost
  gather_facts: no
  vars_files:
    - awskeys.yml
  tasks:
    - name: delete old key
      ec2_key:
        aws_access_key: "{{ AWS_ACCESS_KEY_ID }}"
        aws_secret_key: "{{ AWS_SECRET_ACCESS_KEY }}"
        region: "{{ AWS_REGION }}"
        name: mykeypair
        state: absent
    - name: create a new ec2 keypair
      ec2_key:
        aws_access_key: "{{ AWS_ACCESS_KEY_ID }}"
        aws_secret_key: "{{ AWS_SECRET_ACCESS_KEY }}"
        region: "{{ AWS_REGION }}"
        name: mykeypair
      register: keypair
    - debug:
        var: keypair
    - name: write new private key to file locally
      lineinfile:
        create: yes
        path: /home/mayank/ansibleWorkspace/keypair.pem
        line: "{{ keypair.key.private_key }}"
        mode: 0400
